db.user.insertMany([
    {
        "_id":1,
        "login":"admin",
        "firstname":"",
        "lastname":""
    },
    {
        "_id":2,
        "login":"cardotcl",
        "firstname":"Clément",
        "lastname":"Cardot"
    },
    {
        "_id":3,
        "login":"duboisj",
        "firstname":"Jean",
        "lastname":"Dubois"
    },
    {
        "_id":4,
        "login":"dupontp",
        "firstname":"Pierre",
        "lastname":"Dupont"
    },
    {
        "_id":5,
        "login":"durandm",
        "firstname":"Marie",
        "lastname":"Durand"
    },
    {
        "_id":6,
        "login":"martinj",
        "firstname":"Jean",
        "lastname":"Martin"
    },
    {
        "_id":7,
        "login":"richardt",
        "firstname":"Thomas",
        "lastname":"Richard"
    },
    {
        "_id":8,
        "login":"robertj",
        "firstname":"Jean",
        "lastname":"Robert"
    },
    {
        "_id":9,
        "login":"rouxj",
        "firstname":"Jean",
        "lastname":"Roux"
    },
    {
        "_id":10,
        "login":"vincentm",
        "firstname":"Marie",
        "lastname":"Vincent"
    },
    {
        "_id":11,
        "login":"berthierj",
        "firstname":"Jean",
        "lastname":"Berthier"
    },
    {
        "_id":12,
        "login":"davidm",
        "firstname":"Marie",
        "lastname":"David"
    },
    {
        "_id":13,
        "login":"durandj",
        "firstname":"Jean",
        "lastname":"Durand"
    },
    {
        "_id":14,
        "login":"fontainem",
        "firstname":"Marie",
        "lastname":"Fontaine"
    },
    {
        "_id":15,
        "login":"garciaj",
        "firstname":"Jean",
        "lastname":"Garcia"
    },
    {
        "_id":16,
        "login":"gonzalezm",
        "firstname":"Marie",
        "lastname":"Gonzalez"
    },
    {
        "_id":17,
        "login":"hervej",
        "firstname":"Jean",
        "lastname":"Hervé"
    },
    {
        "_id":18,
        "login":"jeanm",
        "firstname":"Marie",
        "lastname":"Jean"
    }
]);