
# Defines the stages for the GitLab CI/CD pipeline.
# Each stage represents a phase in the pipeline.
# The pipeline will execute the jobs defined in each stage in the order they are defined.
stages:
  - build
  - test
  - sonar
  - release
  - deploy
  - e2e

# Define environment variables for the GitLab CI/CD pipeline
variables:
  HTTP_PROXY_IP: "192.168.4.8"
  HTTP_PROXY_PORT: "3128"
  # Define Maven options for the pipeline, including proxy settings, repository location, and logging configuration
  MAVEN_OPTS: "-Dhttp.proxyHost=$HTTP_PROXY_IP -Dhttp.proxyPort=$HTTP_PROXY_PORT -Dhttps.proxyHost=$HTTP_PROXY_IP -Dhttps.proxyPort=$HTTP_PROXY_PORT -Dhttps.protocols=TLSv1.2 -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"
  # Define Maven CLI options for the pipeline, including batch mode, error handling, and version information
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true"
  # Define the IP address of the development server
  DEV_SERVER_IP: 172.24.1.26
  # Define the username for the development server
  DEV_SERVER_USER: etudiant
  # Define the URL for the Docker image repository
  DOCKER_IMAGE_REPOSITORY_URL: srv-proxy.openstack.etudis.eseo.fr:1971

# This section sets up the environment variables that define the proxy server to be used for the GitLab CI pipeline.
before_script:
  - export https_proxy=http://$HTTP_PROXY_IP:$HTTP_PROXY_PORT/
  - export http_proxy=http://$HTTP_PROXY_IP:$HTTP_PROXY_PORT/

# This job builds the Angular application using Node.js and Angular CLI.
# It installs dependencies, builds the application, and caches the node_modules directory for future builds.
# The resulting build artifacts are stored in the 'front/dist' directory.
# This job is excluded from running for the 'dev' branche.
angular-build:
  stage: build
  image: node:18.18.0-alpine
  script:
    - cd front
    - npm install
    - npm install -g @angular/cli
    - ng build
  cache:
    paths:
      - front/node_modules

# This job builds the Java project using Maven and creates a WAR file.
java-build:
  stage: build
  image: maven:3.8.1-openjdk-17
  script:
    - cd back
    - mvn --log-file $CI_PROJECT_DIR/mvn.log $MAVEN_CLI_OPTS $MAVEN_OPTS clean package -DskipTests=true
  artifacts:
    paths:
      - $CI_PROJECT_DIR/mvn.log
    expire_in: 1 day
    when: always
  cache:
    paths:
      - $CI_PROJECT_DIR/.m2/repository

# This job runs JUnit tests for the project and generates a coverage report.
junit-test:
  stage: test
  image: maven:3.8.1-openjdk-17
  script:
    - cd back
    - mvn --log-file $CI_PROJECT_DIR/mvn.log $MAVEN_CLI_OPTS compile test
    - awk -F"," '{ instructions += $4 + $5; covered += $5 } END { printf "Total Coverage = %.0f%%", 100*covered/instructions }' target/site/jacoco/jacoco.csv
  coverage: '/Total.*?([0-9]{1,3})%/'
  artifacts:
    reports:
      junit: back/target/surefire-reports/TEST*.xml
    paths:
      - back/target/site/jacoco
      - $CI_PROJECT_DIR/mvn.log
    expire_in: 1 day
    when: always
  cache:
    paths:
      - $CI_PROJECT_DIR/.m2/repository
  needs: []


# This file contains the GitLab CI/CD pipeline configuration for the XRL Online project.
# The quality-dev job is responsible for running SonarQube analysis on the project's codebase.
quality-dev:
  stage: sonar
  image: maven:3.8.1-openjdk-17
  script:
    - cd back
    - mvn --log-file $CI_PROJECT_DIR/mvn_clean_compile_test.log $MAVEN_CLI_OPTS clean compile test
    - cd ..
    - mvn --log-file $CI_PROJECT_DIR/mvn_sonar.log $MAVEN_CLI_OPTS validate sonar:sonar -Dsonar.projectKey=xrl_online_project -Dsonar.host.url=http://172.24.1.1:9000/sonar/ -Dsonar.login=$SONAR_TOKEN
  artifacts:
    paths:
      - $CI_PROJECT_DIR/mvn_clean_compile_test.log
      - $CI_PROJECT_DIR/mvn_sonar.log
    expire_in: 1 day
    when: always
  cache:
    paths:
      - $CI_PROJECT_DIR/.m2/repository
  needs:
  - job: junit-test
    artifacts: true
  allow_failure: true # Allow the job to fail and still pass the pipeline
  only:
    - dev
# The above job runs only on the dev branch and depends on the junit-test job, which runs unit tests.

# Define a release stage for the GitLab CI pipeline
release:
  stage: release
  # Define the runner tags for this job
  tags:
    - runner9
  # Define environment variables for this job
  variables:
    DOCKER_TLS_CERTDIR: ""
    DOCKER_HOST: "tcp://docker:2375"
    HTTPS_PROXY: "http://$HTTP_PROXY_IP:$HTTP_PROXY_PORT/"
    HTTP_PROXY: "http://$HTTP_PROXY_IP:$HTTP_PROXY_PORT/"
    NO_PROXY: "192.168.4.8,srv-proxy.openstack.eseo.fr,172.24.0.0/16,docker,gitlab-etu.openstack.etudis.eseo.fr"
  # Define the Docker image to use for this job
  image: docker:24.0.6
  # Define the Docker services to use for this job
  services:
    - docker:24.0.6-dind
  # Add the proxy settings into the maven command for building the image
  before_script:
    # Define the proxy settings for the Tomcat Docker image
    - sed -i "s/RUN mvn clean package -P prod/RUN mvn clean package -P prod -Dhttp.proxyHost=$HTTP_PROXY_IP -Dhttp.proxyPort=$HTTP_PROXY_PORT -Dhttps.proxyHost=$HTTP_PROXY_IP -Dhttps.proxyPort=$HTTP_PROXY_PORT -Dhttps.protocols=TLSv1.2/g" ./Dockerfile
    - sed -i "s,#PLACEHOLDER1,RUN npm config set proxy 'http://$HTTP_PROXY_IP:$HTTP_PROXY_PORT',g" ./Dockerfile
    - sed -i "s,#PLACEHOLDER2,RUN npm config set https-proxy 'http://$HTTP_PROXY_IP:$HTTP_PROXY_PORT',g" ./Dockerfile
    - sed -i "s,#PLACEHOLDER3,RUN pip config set global.proxy 'http://$HTTP_PROXY_IP:$HTTP_PROXY_PORT',g" ./Dockerfile
    # Remove dos2unix command from Dockerfile
    - sed -i '/dos2unix/d' ./db/Dockerfile
  # Define the script to run for this job
  script:
    - docker compose build -q
    - echo $DOCKER_USER
    - echo $DOCKER_PASSWORD | docker login --username $DOCKER_USER --password-stdin docker.io
    - docker compose push
  # Define the branches to run this job on
  only:
    - dev
    - fix-CD

# This file contains the GitLab CI/CD pipeline configuration for deploying the application to the development environment.
deploy:
  stage: deploy
  tags:
    - runner9
  variables:
    DOCKER_TLS_CERTDIR: ""
    DOCKER_HOST: "tcp://docker:2375"
    HTTPS_PROXY: "http://$HTTP_PROXY_IP:$HTTP_PROXY_PORT/"
    HTTP_PROXY: "http://$HTTP_PROXY_IP:$HTTP_PROXY_PORT/"
    NO_PROXY: "192.168.4.8,srv-proxy.openstack.eseo.fr,172.24.0.0/16,docker,gitlab-etu.openstack.etudis.eseo.fr,$DEV_SERVEUR"
  image: docker:24.0.6
  services:
    - docker:24.0.6-dind
  script:
    # starts the SSH agent on the build machine
    - eval $(ssh-agent -s)
    # adds the SSH key to the ssh-agent for GitLab CI/CD pipeline.
    - cat "$DEV_SSH_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - mkdir /root/.ssh && chmod 0700 /root/.ssh
    - ssh-keyscan $DEV_SERVER_IP >> /root/.ssh/known_hosts

    - echo $DOCKER_PASSWORD | docker login --username $DOCKER_USER --password-stdin docker.io
    # Stop active containers + Remove all images, containers, volumes, and networks
    - DOCKER_HOST=ssh://$DEV_SERVER_USER@$DEV_SERVER_IP docker compose down --rmi all -v
    # Pull and start new containers
    - DOCKER_HOST=ssh://$DEV_SERVER_USER@$DEV_SERVER_IP docker compose pull
    - DOCKER_HOST=ssh://$DEV_SERVER_USER@$DEV_SERVER_IP docker compose up -d
  needs:
    - job: release
  only:
    - dev
    - fix-CD

# This GitLab CI configuration file defines a job named "cypress-test" that runs Cypress end-to-end tests.
# The job runs in the "e2e" stage and requires the "deploy" job to be completed successfully before it can run.
# The job runs only on the "dev" branche.
# The job replaces the "localhost" references in the "cypress.config.ts" file with the IP address of the development server.
# The job generates a JUnit report and combines it with other reports in the "front/cypress/results" directory.
# The job sets the npm proxy configuration to use a specific proxy server.
cypress-test:
  stage: e2e
  image: cypress/base:20.9.0
  script:
    - cd front
    # put server IP
    - sed -i "s/localhost:4200/$DEV_SERVER_IP:8080/g" ./cypress.config.ts
    - sed -i "s/localhost:27017/$DEV_SERVER_IP:27017/g" ./cypress.config.ts
    # install dependencies
    - npm config set proxy http://$HTTP_PROXY_IP:$HTTP_PROXY_PORT/
    - npm config set https-proxy http://$HTTP_PROXY_IP:$HTTP_PROXY_PORT/
    - npm install
    # run Cypress tests
    - npm run cypress:run
  after_script:
    - cd front
    # combine junit reports
    - npm run merge-reports
  artifacts:
    reports:
      junit: front/cypress/results/e2e-test-report.xml
    paths:
      - front/cypress/results
    expire_in: 3 day
    when: always
  needs:
    - job: deploy
  only:
    - dev
    - fix-CD
