version: '3'
services:
  mongodb:
    image: xrl-online-db
    build:
      context: db
      dockerfile: Dockerfile
    ports:
      - "27017:27017"
    volumes:
      - ./mongo_backup:/mongo_backup

  tomcat:
    image: xrl-online-tomcat
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    volumes:
      - ./logs:/usr/local/tomcat/logs