services:
  mongodb:
    image: clementcardot/xrl-online-db
    build:
      context: db
      dockerfile: Dockerfile
    ports:
      - "27017:27017"
    volumes:
      - ./db/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
  tomcat:
    image: clementcardot/xrl-online-tomcat
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"