services:
  mongodb:
    build:
      context: bdd
      dockerfile: Dockerfile
    ports:
      - "27017:27017"
    volumes:
      - ./bdd/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
  tomcat:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"