// Insert : Users
const users = db.users.insertMany([
    {
        "login":"admin",
        "firstName":"admin",
        "lastName":"admin"
    },
    {
        "login":"cardotcl",
        "firstName":"Clément",
        "lastName":"Cardot"
    },
    {
        "login":"duboisj",
        "firstName":"Jean",
        "lastName":"Dubois"
    },
    {
        "login":"dupontp",
        "firstName":"Pierre",
        "lastName":"Dupont"
    },
    {
        "login":"durandm",
        "firstName":"Marie",
        "lastName":"Durand"
    },
    {
        "login":"martinj",
        "firstName":"Jean",
        "lastName":"Martin"
    },
    {
        "login":"richardt",
        "firstName":"Thomas",
        "lastName":"Richard"
    },
    {
        "login":"robertj",
        "firstName":"Jean",
        "lastName":"Robert"
    },
    {
        "login":"rouxj",
        "firstName":"Jean",
        "lastName":"Roux"
    },
    {
        "login":"vincentm",
        "firstName":"Marie",
        "lastName":"Vincent"
    },
    {
        "login":"berthierj",
        "firstName":"Jean",
        "lastName":"Berthier"
    },
    {
        "login":"davidm",
        "firstName":"Marie",
        "lastName":"David"
    },
    {
        "login":"durandj",
        "firstName":"Jean",
        "lastName":"Durand"
    },
    {
        "login":"fontainem",
        "firstName":"Marie",
        "lastName":"Fontaine"
    },
    {
        "login":"garciaj",
        "firstName":"Jean",
        "lastName":"Garcia"
    },
    {
        "login":"gonzalezm",
        "firstName":"Marie",
        "lastName":"Gonzalez"
    },
    {
        "login":"hervej",
        "firstName":"Jean",
        "lastName":"Hervé"
    },
    {
        "login":"jeanm",
        "firstName":"Marie",
        "lastName":"Jean"
    }
]);

