cat init_database.js > mongo-init.js
cat DB_Collections/user.js >> mongo-init.js
cat DB_Collections/team.js >> mongo-init.js
cat DB_Collections/business_line.js >> mongo-init.js
cat DB_Collections/readiness_level.js >> mongo-init.js
cat DB_Collections/project.js >> mongo-init.js
cat DB_Insert/user.js >> mongo-init.js
cat DB_Insert/team.js >> mongo-init.js
cat DB_Insert/business_line.js >> mongo-init.js
cat DB_Insert/readiness_level.js >> mongo-init.js
cat DB_Insert/project.js >> mongo-init.js